spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  resources:
    chain.strategy.content:
      enabled: true
      paths: /**
  session.jdbc.initialize-schema: "always"

