spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.url: "jdbc:mysql://134.0.119.88:3306/test?encoding=UTF8"
spring.datasource.username: "root"
spring.datasource.password: "728s!PIvo4cF8trUw"
spring.jpa.generate-ddl: true
spring.resources.chain.strategy.content.enabled: true
spring.resources.chain.strategy.content.paths: /**
spring.session.jdbc.initialize-schema: "always"
