application:
  storage:
    upload:
      main: 'C:\Users\sugar\Desktop\Muskrat\Qwik\Backend\img\'
      shop: 'shop\'
      product: 'product\'
  jwt:
    token:
      secret: '5HwEKY7Y8jOfzGYK'
      expired: 3600000
  order:
    irrevocable-status: 5
geocode:
  app.id: 'PwhAzeVFHuSMGdcjtFvQ'
  app.code: 'yE6QWws10hfiJKPyLE-hIQ'
  country: 'MYS'
  complete:
    maxresults: 5
server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: 'password'
  liquibase:
    url: 'jdbc:h2:mem:testdb'
    user: 'sa'
    password: 'password'
    change-log: 'classpath:liquibase/db.changelog-master.xml'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        #enable_lazy_load_no_trans: true
        #        show_sql: true
        user_sql_comments: true
        format_sql: true
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
  resources:
    chain.strategy.content:
      enabled: true
      paths: /**
  session.jdbc.initialize-schema: "always"

